spring.application.name=driver-vehicle-service
server.port=8083
spring.profiles.default=local

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=ridelink
spring.data.mongodb.auto-index-creation=true

ridelink.security.admin.username=${AUTH_ADMIN_USERNAME}
ridelink.security.admin.password=${AUTH_ADMIN_PASSWORD}
ridelink.security.jwt.secret=${JWT_SECRET}
ridelink.security.jwt.expiration=PT15M

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
