spring.application.name=ride-service
server.port=8080

# MongoDB Atlas Configuration
spring.data.mongodb.uri=${RIDE_MONGODB_URI}

# SpringDoc OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

driver-vehicle-service.base-url=${DRIVER_VEHICLE_SERVICE_URL:http://localhost:8083/api/v1}
driver-vehicle-service.auth.username=${DRIVER_SERVICE_USERNAME}
driver-vehicle-service.auth.password=${DRIVER_SERVICE_PASSWORD}

jwt.secret=${JWT_SECRET}

