spring.application.name=ride-service
server.port=8080

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb://chamiduwimanthadampahalage_db_user:123123123@ac-nkeue6x-shard-00-00.s5w47yw.mongodb.net:27017,ac-nkeue6x-shard-00-01.s5w47yw.mongodb.net:27017,ac-nkeue6x-shard-00-02.s5w47yw.mongodb.net:27017/?ssl=true&replicaSet=atlas-b9o8qy-shard-0&authSource=admin&appName=RideLink

# SpringDoc OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html